import type { NextPage } from 'next';
import Head from 'next/head';
import getAssetUrl from '../lib/assets';

const Home: NextPage = () => {
  return (
    <div className="px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center">
        <h1 className="text-center text-6xl">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="my-16 text-center text-2xl">
          Get started by editing <code>pages/index.tsx</code>
        </p>
      </main>
      <footer>
        <span className="h-[1em] ml-2">
          <img src={getAssetUrl('vercel.svg')} alt="" />
        </span>
      </footer>
    </div>
  );
};

export default Home;
